# This file stores configurations for your Shopify app

scopes = "write_products,read_products,write_discounts,read_discounts,write_orders,read_orders,write_customers,read_customers"

[access_scopes]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://your-app-domain.com/auth/callback",
  "https://your-app-domain.com/auth/shopify/callback",
  "https://your-app-domain.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://your-app-domain.com/proxy"
subpath = "discount-manager"
prefix = "apps"

[pos]
embedded = false